os:
  - osx

osx_image: xcode8.1
language: generic

before_install:
  - gem install --verbose xcpretty

script:
  - mkdir ${PWD}/__build__
  - set -o pipefail && xcodebuild -configuration Release -target "MumbleKit (iOS)" CONFIGURATION_BUILD_DIR="${PWD}/__build__" | xcpretty
